---
- name: Converge
  hosts: all
  become: true

  vars:
    apache_vhosts:
      - apache_vhost_name: "example.com"
        servername: "example.com"
        documentroot: "/var/www/vhosts/example_com"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: apham0001.apache
